CREATE TABLE [dbo].[Users](
	[UserId] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [NVARCHAR](250) NOT NULL,
	[Email] [NVARCHAR](250) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
